name: Python application test with GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      # use the current checkout action

      - name: Set up Python 3.10
        uses: actions/setup-python@v5   # v5 correctly resolves “3.10”
        with:
          python-version: '3.10'        # latest 3.10.x

      - name: Install dependencies
        run: |
          make install
